import os

######## function to view the directory tree generated by os.walk

def print_directory_tree(root_dir, padding='', print_files=True):
    """
    Print the directory tree structure.

    :param root_dir: The root directory to start the tree from.
    :param padding: Padding for the current level in the directory tree.
    :param print_files: Whether to print files in the directory tree.
    """
    print(padding[:-1] + '+--' + os.path.basename(root_dir) + '/')
    padding = padding + '   '

    for root, dirs, files in os.walk(root_dir):
        for directory in dirs:
            print_directory_tree(os.path.join(root, directory), padding, print_files)
        if print_files:
            for file in files:
                print(padding + '+--' + file)
        break  # To prevent os.walk from going into subdirectories multiple times
